config/routes.rb
Rails.application.routes.draw do

  get 'temps/receive' => 'temps#receive'

  resources :temps

  root 'temps#dashboard'

end

app/models/temp.rb
class Temp < ActiveRecord::Base
require 'httparty'

def self.gettemp_internal
 r = HTTParty.get("http://admin.local/arduino/on/")
 r.parsed_response.to_f
end

def self.gettemp_external
 w = WeatherUnderground::Base.new
 w.CurrentObservations( '98102' ).temp_f.to_f
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/temps_controller.rb
class TempsController < ApplicationController
  before_action :set_temp, only: [:show, :edit, :update, :destroy]

  # GET /temps
  # GET /temps.json

  def index
    @temps = Temp.all
  end

  def dashboard
    @daytemps = Temp.where("created_at > ?", Time.now-1.days)
    @weektemps = Temp.where("created_at > ?", Time.now-7.days)
  end


  # GET /temps/1
  # GET /temps/1.json
  def show
  end

  def receive
  #raise params[:temp].to_yaml
   t = Temp.new
   t.insidetemp = params[:temp]
   t.outsidetemp = Temp.gettemp_external
   t.save
   redirect_to root_url
  end

  # GET /temps/new
  def new
    @temp = Temp.new
  end

  # GET /temps/1/edit
  def edit
  end

  # POST /temps
  # POST /temps.json
  def create
    @temp = Temp.new(temp_params)

    respond_to do |format|
      if @temp.save
        format.html { redirect_to @temp, notice: 'Temp was successfully created.' }
        format.json { render :show, status: :created, location: @temp }
      else
        format.html { render :new }
        format.json { render json: @temp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /temps/1
  # PATCH/PUT /temps/1.json
  def update
    respond_to do |format|
      if @temp.update(temp_params)
        format.html { redirect_to @temp, notice: 'Temp was successfully updated.' }
        format.json { render :show, status: :ok, location: @temp }
      else
        format.html { render :edit }
        format.json { render json: @temp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temps/1
  # DELETE /temps/1.json
  def destroy
    @temp.destroy
    respond_to do |format|
      format.html { redirect_to temps_url, notice: 'Temp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_temp
      @temp = Temp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def temp_params
      params.require(:temp).permit(:insidetemp, :outsidetemp)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/temps_helper.rb
module TempsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tempapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
  <%= stylesheet_link_tag 'http://yandex.st/bootstrap/3.1.1/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'http://yandex.st/bootstrap/3.1.1/js/bootstrap.min.js' %>
  
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/temps/_form.html.erb
<%= form_for(@temp) do |f| %>
  <% if @temp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@temp.errors.count, "error") %> prohibited this temp from being saved:</h2>

      <ul>
      <% @temp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :insidetemp %><br>
    <%= f.text_field :insidetemp %>
  </div>
  <div class="field">
    <%= f.label :outsidetemp %><br>
    <%= f.text_field :outsidetemp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/temps/dashboard.html.erb
<br>



 <% o = @daytemps.group_by_minute(:created_at).maximum(:outsidetemp)%>
<% i = @daytemps.group_by_minute(:created_at).maximum(:insidetemp)%>

<%= line_chart [
  {name: "Insdie", data: i,},
  {name: "Outside", data: o}

], min: 40, max: 110, height: "500px" %>
<center>
Current Outside: <%=@daytemps.last.outsidetemp%><br>
Current Inside: <%=@daytemps.last.insidetemp%>
</center>

<% o = @weektemps.group_by_hour(:created_at).maximum(:outsidetemp)%>
<% i = @weektemps.group_by_hour(:created_at).maximum(:insidetemp)%>

<%= line_chart [
 {name: "Insdie", data: i,},
 {name: "Outside", data: o}

], min: 40, max: 110, height: "500px" %>

app/views/temps/edit.html.erb
<h1>Editing temp</h1>

<%= render 'form' %>

<%= link_to 'Show', @temp %> |
<%= link_to 'Back', temps_path %>

app/views/temps/index.html.erb
<h1>Listing temps</h1>
<%=@temps.count%>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Insidetemp</th>
      <th>Outsidetemp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @temps.each do |temp| %>
      <tr>
        <td><%= temp.insidetemp %></td>
        <td><%= temp.outsidetemp %></td>
        <td><%= temp.created_at.strftime("%H:%M:%S") %></td>
        <td><%= link_to 'Edit', edit_temp_path(temp) %></td>
        <td><%= link_to 'Destroy', temp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/temps/new.html.erb
<h1>New temp</h1>

<%= render 'form' %>

<%= link_to 'Back', temps_path %>

app/views/temps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Insidetemp:</strong>
  <%= @temp.insidetemp %>
</p>

<p>
  <strong>Outsidetemp:</strong>
  <%= @temp.outsidetemp %>
</p>

<%= link_to 'Edit', edit_temp_path(@temp) %> |
<%= link_to 'Back', temps_path %>